# Android 构建配置
# 请根据你的系统设置 ANDROID_NDK_HOME 环境变量

[target.aarch64-linux-android]
linker = "aarch64-linux-android30-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi30-clang"

[target.i686-linux-android]
linker = "i686-linux-android30-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android30-clang"

# 优化配置
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
